/** Perform6 JS↔autorun command-bus message types (BrightSign pipe payload). */
export const AUTORUN_PROTOCOL_VERSION = 2;

export const BridgeMsg = {
  HELLO: 'led-hello',
  HELLO_ACK: 'led-hello-ack',
  PING: 'led-bridge-ping',
  PONG: 'led-bridge-pong',
  TICK: 'led-bridge-tick',
  HEALTHY: 'led-bridge-healthy',
  HEAL: 'led-bridge-heal',
  RECYCLE: 'led-bridge-recycle-html',
  RECYCLE_ACK: 'led-bridge-recycle-ack',
  XT_PLAYBACK: 'xt-playback',
  XT_PLAYBACK_ACK: 'xt-playback-ack',
  XT_LED_READY: 'xt-led-ready',
  XT_LED_ENDED: 'xt-led-ended',
  XC_PLAYBACK: 'xc-playback',
  XC_PLAYBACK_ACK: 'xc-playback-ack',
  XC_LED_READY: 'xc-led-ready',
  CACHE_PREFETCH: 'led-cache-prefetch',
  CACHE_KEEP: 'led-cache-keep',
  CACHE_EVICT: 'led-cache-evict',
  CACHE_CANCEL: 'led-cache-cancel',
  CACHE_CLEAR_ALL: 'led-cache-clear-all',
  CACHE_PROGRESS: 'led-cache-progress',
  OTA_PING: 'led-ota-ping',
  OTA_AUTH: 'led-ota-auth',
  OTA_INSTALL: 'led-ota-install',
  OTA_CANCEL: 'led-ota-cancel',
  OTA_REBOOT: 'led-ota-reboot',
  OTA_PROGRESS: 'led-ota-progress',
  FS_LIST: 'led-fs-list',
  FS_READ: 'led-fs-read',
  FS_WRITE: 'led-fs-write',
  FS_DELETE: 'led-fs-delete',
  FS_RESULT: 'led-fs-result',
  STORAGE_INFO: 'led-storage-info',
  STORAGE_INFO_RESULT: 'led-storage-info-result',
  STORAGE: 'led-storage',
  LOG_TAIL_REQUEST: 'led-log-tail-request',
  LOG_TAIL: 'led-log-tail',
  OPS_RELOAD: 'led-ops-reload',
  OPS_WRITE: 'led-ops-write',
  OPS_CONFIG: 'led-ops-config',
} as const;

export type BridgeMsgType = (typeof BridgeMsg)[keyof typeof BridgeMsg];
